version: "3.9"

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      ConnectionStrings__MyDbContext: "Server=db;Database=IPediDb;User=sa;Password=123;"
